platform :ios, '14.0'
source "https://cdn.cocoapods.org/"
project "RxRealmDemo.xcodeproj"
use_frameworks!

def common
  pod "RxRealm", :path => "../"
end

def common_tests
  pod "RxBlocking", "~> 6.0"
end

target "RxRealmDemo-iOS" do
  common
end

# target "RxRealmDemo-macOS" do
#   platform :osx, "10.12"
#   common
# end

# target "RxRealmDemo-tvOS" do
#   platform :tvos, "9.0"
#   common
# end
